// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkvNESee773M0Faat87_kPHDjrkK3IDsk',
    appId: '1:926465127760:web:396e60944d5b52b9c96855',
    messagingSenderId: '926465127760',
    projectId: 'chatappfirebase-7dcd4',
    authDomain: 'chatappfirebase-7dcd4.firebaseapp.com',
    storageBucket: 'chatappfirebase-7dcd4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7hey4DA9iYqIFtyldlonstY4iUXQgU6Y',
    appId: '1:926465127760:android:fcfeb675adf0ce1fc96855',
    messagingSenderId: '926465127760',
    projectId: 'chatappfirebase-7dcd4',
    storageBucket: 'chatappfirebase-7dcd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH7e1BpJB3aXLyKXfLYrzh5XbZUnmgoy4',
    appId: '1:926465127760:ios:57ee5c2a770dca4ac96855',
    messagingSenderId: '926465127760',
    projectId: 'chatappfirebase-7dcd4',
    storageBucket: 'chatappfirebase-7dcd4.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH7e1BpJB3aXLyKXfLYrzh5XbZUnmgoy4',
    appId: '1:926465127760:ios:57ee5c2a770dca4ac96855',
    messagingSenderId: '926465127760',
    projectId: 'chatappfirebase-7dcd4',
    storageBucket: 'chatappfirebase-7dcd4.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkvNESee773M0Faat87_kPHDjrkK3IDsk',
    appId: '1:926465127760:web:c094c0b4f504a786c96855',
    messagingSenderId: '926465127760',
    projectId: 'chatappfirebase-7dcd4',
    authDomain: 'chatappfirebase-7dcd4.firebaseapp.com',
    storageBucket: 'chatappfirebase-7dcd4.firebasestorage.app',
  );
}
